Repository openyurtio/yurtcluster-operator, pull requests merged in 2022-03, with the labels that each got.

#20 agent: do not add taint for edge node automatically
  pkg/controllers/agent/yurtcluster_controller.go
  pkg/util/kubernetes.go
Labels: approved, lgtm, size/M, cleanup

#21 agent: do not add taint for edge node
  pkg/controllers/agent/yurtcluster_controller.go
  pkg/util/kubernetes.go
Labels: approved, lgtm, size/M, cleanup

#22 bump openyurt version to v0.6.1
  Makefile
  api/v1alpha1/defaults.go
  charts/charts/yurt-controller-manager/values.yaml
  charts/values.yaml
  config/samples/operator_v1alpha1_yurtcluster.yaml
Labels: approved, kind/feature, lgtm, size/M

#23 bump version to v0.6.2
  Makefile
  charts/Chart.yaml
  charts/values.yaml
  config/agent/agent.yaml
  config/agent/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  docs/manifests/deploy.yaml
Labels: approved, lgtm, size/S, kind/cleanup

#24 bump openyurt version to v0.6.1
  Makefile
  api/v1alpha1/defaults.go
  charts/Chart.yaml
  charts/charts/yurt-controller-manager/values.yaml
  charts/values.yaml
  config/samples/operator_v1alpha1_yurtcluster.yaml
Labels: approved, lgtm, size/M, kind/cleanup

#19 add reconcile event for trace node convert
  pkg/controllers/agent/yurtcluster_controller.go
Labels: approved, kind/enhancement, lgtm, size/S
